<script src="https://code.jquery.com/jquery-3.7.0.slim.min.js" type="text/javascript" charset="utf8"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" type="text/javascript" charset="utf8"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" type="text/javascript" charset="utf8"></script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js" type="text/javascript" charset="utf8"></script>
<script src="https://cdn.datatables.net/plug-ins/1.13.4/sorting/date-de.js" type="text/javascript" charset="utf8"></script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js" type="text/javascript" charset="utf8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js" type="text/javascript" charset="utf8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js" type="text/javascript" charset="utf8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js" type="text/javascript" charset="utf8"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js" type="text/javascript" charset="utf8"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js" type="text/javascript" charset="utf8"></script>